### PR TITLE
Port to 1.12 and french translation update

### PR DESCRIPTION
**Pull request by Pyrofab**
Since I've ported your mod to 1.12 for personal use, I figured I might as well give you what I've done. The only thing that is left to do is port the custom IRecipe for the boomerang enchantment and the nest of bees.
That would likely take custom recipe factories with the new system. Also, I used vanilla minecraft IDs for the recipes instead of oredictionnary. Apart from that, nothing seems broken from what I can tell.

Oh and I took the opportunity to update the french translation. The google translate game was a bit strong sometimes.

### CODE REVIEW

**Comment by ThexXTURBOXx** [comment]
Oh, uhm... Wow, thank you for your work! I will take a look at every change you have done to verify, if everything is right. But for now it looks awesome.
The recipes shouldn't be a big deal (I hope). They just need some time, because my whole day is pretty much planned. :(

**Comment by Pyrofab** [comment]
No problem :)

**Comment by ThexXTURBOXx** [comment]
Okay, I looked over your changes. Very nice work! I will merge it and add the custom RecipeFactories. Let's see how this goes out ;)

**Comment by ThexXTURBOXx** [comment]
Ok, I merged it and changed everything, I wanted to change. If you want, clone the 1.12-branch and test it out. If you find any bugs, simply comment on this issue: #173

**Pull request merged**
